In [0]:
import numpy as np
import matplotlib.pyplot as plt
import torch

## 1. Initialise Tensors

In [0]:
x = torch.ones(3,2)
x

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [0]:
x = torch.empty(3,2)
print(x)
y = torch.zeros_like(x)
print(y)

tensor([[4.0014e-37, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [0]:
x = torch.linspace(0,1,steps=5)
print(x)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [0]:
x = torch.tensor([[1,2],[3,4],[5,6]])
print(x)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


## 2. Slicing Tensors

In [0]:
print(x.size())
print(x[:,1])
print(x[0,:])

torch.Size([3, 2])
tensor([2, 4, 6])
tensor([1, 2])


In [0]:
y = x[1,1]
print(y)
print(y.item())

tensor(4)
4


## 3. Reshaping of tensors

In [0]:
print(x)
y = x.view(2,3)
print(y)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [0]:
y = x.view(6,-1)
print(y)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


## 4. Simple Tensor Operations

In [0]:
x = torch.ones([3,2])
y = torch.ones([3,2])

# these are element wise operations
z = x + y
print(z)
z = x - y
print(z)
z = x * y
print(z)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [0]:
z = y.add(x)
print(z)
print(y)
z = y.add_(x)
print(z)
print(y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


## 5. Numpy <> PyTorch

In [0]:
x_np = x.numpy()
print(type(x_np),type(x))
print(x_np)

<class 'numpy.ndarray'> <class 'torch.Tensor'>
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [0]:
# converting numpy array to tensor
a = np.random.rand(5)
a_pt = torch.from_numpy(a)
print(type(a_pt),type(a))
print(a_pt)

<class 'torch.Tensor'> <class 'numpy.ndarray'>
tensor([0.5003, 0.6073, 0.8963, 0.7934, 0.8323], dtype=torch.float64)


In [0]:
np.add(a,1,out=a)
print(a)
print(a_pt)

# the point wise addition is added to the tensor as well as it is refered to the same numpy array

[1.50025261 1.60726455 1.89627034 1.79337122 1.83227643]
tensor([1.5003, 1.6073, 1.8963, 1.7934, 1.8323], dtype=torch.float64)


## 6. Speed Comparison between Numpy and Pytorch

In [0]:
%%time
for i in range(100):
  a = np.random.rand(100,100)
  b = np.random.rand(100,100)
  c = np.matmul(a,b)

CPU times: user 53.9 ms, sys: 47.1 ms, total: 101 ms
Wall time: 69.7 ms


In [0]:
%%time
for i in range(100):
  a = torch.randn([100,100])
  b = torch.randn([100,100])
  c = torch.matmul(a,b)

CPU times: user 42.6 ms, sys: 31 ms, total: 73.6 ms
Wall time: 37.1 ms


## 7. Pytorch with GPU

In [0]:
print(torch.cuda.device_count())

1


In [0]:
print(torch.cuda.device(0))
print(torch.cuda.get_device_name(0))
print(torch.cuda.torch.cuda.get_device_properties(0))

Tesla T4
_CudaDeviceProperties(name='Tesla T4', major=7, minor=5, total_memory=15079MB, multi_processor_count=40)


In [0]:
cuda0 = torch.device('cuda:0') #storing the device for further usage

a = torch.ones(3,2,device=cuda0)
b = torch.ones(3,2,device=cuda0)
c = a + b
print(c)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]], device='cuda:0')


In [0]:
%%time
for i in range(10):
  a = np.random.rand(10000,10000)
  b = np.random.rand(10000,10000)
  c = np.add(a,b)

CPU times: user 21.8 s, sys: 104 ms, total: 22 s
Wall time: 22 s


In [0]:
%%time
for i in range(10):
  a = torch.randn([10000,10000])
  b = torch.randn([10000,10000])
  c = torch.add(a,b)

CPU times: user 19.3 s, sys: 114 ms, total: 19.4 s
Wall time: 19.4 s


In [0]:
%%time
for i in range(10):
  a = torch.randn([10000,10000], device = cuda0)
  b = torch.randn([10000,10000], device = cuda0)
  c = torch.add(a,b)

CPU times: user 332 µs, sys: 13.9 ms, total: 14.3 ms
Wall time: 15.9 ms


In [0]:
%%time
for i in range(10):
  a = np.random.rand(10000,10000)
  b = np.random.rand(10000,10000)
  c = np.matmul(a,b)

CPU times: user 15min 54s, sys: 2.63 s, total: 15min 57s
Wall time: 8min 14s


In [0]:
%%time
for i in range(10):
  a = torch.randn([10000,10000])
  b = torch.randn([10000,10000])
  c = torch.matmul(a,b)

CPU times: user 4min 1s, sys: 221 ms, total: 4min 1s
Wall time: 4min 1s


In [0]:
%%time
for i in range(10):
  a = torch.randn([10000,10000], device = cuda0)
  b = torch.randn([10000,10000], device = cuda0)
  c = torch.matmul(a,b)

CPU times: user 6.46 ms, sys: 21 ms, total: 27.4 ms
Wall time: 36.6 ms


## 8. Autograd  / Automatic Differentiation

In [0]:
x = torch.ones([3,2], requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)


In [0]:
y = x + 5
print(y)

tensor([[6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)


In [0]:
z = y*y + 1
print(z)

tensor([[37., 37.],
        [37., 37.],
        [37., 37.]], grad_fn=<AddBackward0>)


In [0]:
t = torch.sum(z)
print(t)

tensor(222., grad_fn=<SumBackward0>)


In [0]:
t.backward()
print(x.grad)

tensor([[12., 12.],
        [12., 12.],
        [12., 12.]])


In [0]:
# Forward Pass
x = torch.ones([3,2], requires_grad=True)
y = x + 5
r = 1/(1+torch.exp(-y))

print(r)

t = torch.sum(r)

# Now we will use the PyTorch Autograd Backward pass
t.backward()
print(x.grad)

tensor([[0.9975, 0.9975],
        [0.9975, 0.9975],
        [0.9975, 0.9975]], grad_fn=<MulBackward0>)
tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


In [0]:
# Forward Pass
x = torch.ones([3,2], requires_grad=True)
y = x + 5
r = 1/(1+torch.exp(-y))

print(r)

s = torch.sum(r)

# Now we will use the PyTorch Autograd Backward pass

# Note that the grad function is done only on scalar values like torch.sum
# but we can calculate the derivative of a tensor by giving an argument in backward function
a = torch.ones([3,2])
r.backward(a)
print(x.grad)

tensor([[0.9975, 0.9975],
        [0.9975, 0.9975],
        [0.9975, 0.9975]], grad_fn=<MulBackward0>)
tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


$$ \frac{\partial s}{\partial x} = \frac{\partial s}{\partial r} + \frac{\partial r}{\partial x}$$



this argument is needed when we want the derivative of the tensors apart from scalar ones

## 9. Learning data using autograd function of pytorch

In [0]:
x = torch.randn([20,1])
y = 3*x - 2  # model

w = torch.ones([1], requires_grad=True)
b = torch.ones([1], requires_grad=True)

learning_rate = 0.1

print(w.item(),b.item())
print(torch.sum((y_pred - y)**2))

y_pred = w*x - b # prediction using the model
# computing the loss
loss_mse = torch.sum((y_pred - y)**2)
loss_mse.backward()
# weight update
w = w - learning_rate*w.grad
b = b - learning_rate*b.grad

print(w.item(),b.item())
print(torch.sum((y_pred - y)**2))

1.0 1.0
tensor(284.5830, grad_fn=<SumBackward0>)
11.475749015808105 8.289739608764648
tensor(141.2062, grad_fn=<SumBackward0>)


In [0]:
%%time
# Now running it for several epochs
N = 1000000
epochs= 200

# 1. True Data
x = torch.randn([N])
y = torch.dot(3*torch.ones([N]),x) - 2

# Initialising the weigths and biases
w = torch.ones([N], requires_grad=True)  # w1*x1 + ....Wn*Xn + b = y 
b = torch.ones([1], requires_grad=True)  # bias term
print(w)

learning_rate = 0.1

for i in range(epochs):
  
  y_pred = torch.dot(w,x) + b # prediction using the model
  # computing the loss
  loss_mse = torch.sum((y_pred - y)**2)

  loss_mse.backward()
  
  with torch.no_grad():
    w -= learning_rate*w.grad
    b -= learning_rate*b.grad
    
    w.grad.zero_()
    b.grad.zero_()

tensor([1., 1., 1.,  ..., 1., 1., 1.], requires_grad=True)
CPU times: user 569 ms, sys: 22 ms, total: 591 ms
Wall time: 602 ms


In [0]:
%%time
# With GPU
# Now running it for several epochs 

N = 1000000
epochs= 200

# 1. True Data
x = torch.randn([N], device=cuda0)
b = torch.randn([1], device=cuda0)
y = torch.dot(3*torch.ones([N], device=cuda0),x) - b

# Initialising the weigths and biases
w = torch.ones([N], requires_grad=True, device=cuda0)  # w1*x1 + ....Wn*Xn + b = y 
b = torch.ones([1], requires_grad=True, device=cuda0)  # bias term
print(w)

learning_rate = 0.1

for i in range(epochs):
  
  y_pred = torch.dot(w,x) + b # prediction using the model
  # computing the loss
  loss_mse = torch.sum((y_pred - y)**2)

  loss_mse.backward()
  
  with torch.no_grad():
    w -= learning_rate*w.grad
    b -= learning_rate*b.grad
    
    w.grad.zero_()
    b.grad.zero_()

  # weight update
  
print(w)

tensor([1., 1., 1.,  ..., 1., 1., 1.], device='cuda:0', requires_grad=True)
tensor([nan, nan, nan,  ..., nan, nan, nan], device='cuda:0',
       requires_grad=True)
CPU times: user 128 ms, sys: 21.1 ms, total: 149 ms
Wall time: 146 ms
